run:
  simulations_per_permutation: 1
  n_workers: 1
  light_profile: INTERPOL
  instruments: #(LSST, DES, Euclid, Roman_VIS)
    - Roman_VIS
  dm_types: #(CDM, WDM, SIDM, Axion)
    - SIDM
  output_dir: output_data

data:
  hsc_catalog: input_data/deeplens_update.hdf5
  lenspop_flow_checkpoint: checkpoints/trained_Lenspop_flow.pt
  camels_flow_checkpoint: checkpoints/trained_Camels_flow.pt

output:
  save_format: hdf5
  save_intermediate: false
